import { createPagesFunctionHandler } from "@react-router/cloudflare"
import { getLoadContext } from "../load-context"

export const onRequest = createPagesFunctionHandler({
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - the server build file is generated by `remix vite:build`
  build: () => import("../build/server"),
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - the server build file is generated by `remix vite:build`
  getLoadContext,
})
