/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as authRoutesLoginRouteImport } from './auth/routes/login'
import { Route as contentRoutesLayoutRouteImport } from './content/routes/layout'
import { Route as blogRoutesIndexRouteImport } from './blog/routes/index'
import { Route as paymentsRoutesWebhookRouteImport } from './payments/routes/webhook'
import { Route as paymentsRoutesSuccessRouteImport } from './payments/routes/success'
import { Route as emailRoutesSentRouteImport } from './email/routes/sent'
import { Route as contentRoutesTermsAndConditionsRouteImport } from './content/routes/terms-and-conditions'
import { Route as contentRoutesPrivacyRouteImport } from './content/routes/privacy'
import { Route as contentRoutesHomeRouteImport } from './content/routes/home'
import { Route as blogRoutesPostRouteImport } from './blog/routes/post'

const authRoutesLoginRoute = authRoutesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const contentRoutesLayoutRoute = contentRoutesLayoutRouteImport.update({
  id: '/_content-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const blogRoutesIndexRoute = blogRoutesIndexRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => contentRoutesLayoutRoute,
} as any)
const paymentsRoutesWebhookRoute = paymentsRoutesWebhookRouteImport.update({
  id: '/payments/webhook',
  path: '/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const paymentsRoutesSuccessRoute = paymentsRoutesSuccessRouteImport.update({
  id: '/payments/success',
  path: '/payments/success',
  getParentRoute: () => rootRouteImport,
} as any)
const emailRoutesSentRoute = emailRoutesSentRouteImport.update({
  id: '/emails/sent',
  path: '/emails/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const contentRoutesTermsAndConditionsRoute =
  contentRoutesTermsAndConditionsRouteImport.update({
    id: '/terms-and-conditions',
    path: '/terms-and-conditions',
    getParentRoute: () => contentRoutesLayoutRoute,
  } as any)
const contentRoutesPrivacyRoute = contentRoutesPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => contentRoutesLayoutRoute,
} as any)
const contentRoutesHomeRoute = contentRoutesHomeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => contentRoutesLayoutRoute,
} as any)
const blogRoutesPostRoute = blogRoutesPostRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => contentRoutesLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof contentRoutesHomeRoute
  '/login': typeof authRoutesLoginRoute
  '/privacy': typeof contentRoutesPrivacyRoute
  '/terms-and-conditions': typeof contentRoutesTermsAndConditionsRoute
  '/emails/sent': typeof emailRoutesSentRoute
  '/payments/success': typeof paymentsRoutesSuccessRoute
  '/payments/webhook': typeof paymentsRoutesWebhookRoute
  '/blog': typeof blogRoutesIndexRoute
  '/blog/$slug': typeof blogRoutesPostRoute
}
export interface FileRoutesByTo {
  '/login': typeof authRoutesLoginRoute
  '/': typeof contentRoutesHomeRoute
  '/privacy': typeof contentRoutesPrivacyRoute
  '/terms-and-conditions': typeof contentRoutesTermsAndConditionsRoute
  '/emails/sent': typeof emailRoutesSentRoute
  '/payments/success': typeof paymentsRoutesSuccessRoute
  '/payments/webhook': typeof paymentsRoutesWebhookRoute
  '/blog': typeof blogRoutesIndexRoute
  '/blog/$slug': typeof blogRoutesPostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_content-layout': typeof contentRoutesLayoutRouteWithChildren
  '/login': typeof authRoutesLoginRoute
  '/_content-layout/': typeof contentRoutesHomeRoute
  '/_content-layout/privacy': typeof contentRoutesPrivacyRoute
  '/_content-layout/terms-and-conditions': typeof contentRoutesTermsAndConditionsRoute
  '/emails/sent': typeof emailRoutesSentRoute
  '/payments/success': typeof paymentsRoutesSuccessRoute
  '/payments/webhook': typeof paymentsRoutesWebhookRoute
  '/_content-layout/blog': typeof blogRoutesIndexRoute
  '/_content-layout/blog/$slug': typeof blogRoutesPostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms-and-conditions'
    | '/emails/sent'
    | '/payments/success'
    | '/payments/webhook'
    | '/blog'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/privacy'
    | '/terms-and-conditions'
    | '/emails/sent'
    | '/payments/success'
    | '/payments/webhook'
    | '/blog'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/_content-layout'
    | '/login'
    | '/_content-layout/'
    | '/_content-layout/privacy'
    | '/_content-layout/terms-and-conditions'
    | '/emails/sent'
    | '/payments/success'
    | '/payments/webhook'
    | '/_content-layout/blog'
    | '/_content-layout/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  contentRoutesLayoutRoute: typeof contentRoutesLayoutRouteWithChildren
  authRoutesLoginRoute: typeof authRoutesLoginRoute
  emailRoutesSentRoute: typeof emailRoutesSentRoute
  paymentsRoutesSuccessRoute: typeof paymentsRoutesSuccessRoute
  paymentsRoutesWebhookRoute: typeof paymentsRoutesWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authRoutesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_content-layout': {
      id: '/_content-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof contentRoutesLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_content-layout/blog': {
      id: '/_content-layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof blogRoutesIndexRouteImport
      parentRoute: typeof contentRoutesLayoutRoute
    }
    '/payments/webhook': {
      id: '/payments/webhook'
      path: '/payments/webhook'
      fullPath: '/payments/webhook'
      preLoaderRoute: typeof paymentsRoutesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/success': {
      id: '/payments/success'
      path: '/payments/success'
      fullPath: '/payments/success'
      preLoaderRoute: typeof paymentsRoutesSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/sent': {
      id: '/emails/sent'
      path: '/emails/sent'
      fullPath: '/emails/sent'
      preLoaderRoute: typeof emailRoutesSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_content-layout/terms-and-conditions': {
      id: '/_content-layout/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof contentRoutesTermsAndConditionsRouteImport
      parentRoute: typeof contentRoutesLayoutRoute
    }
    '/_content-layout/privacy': {
      id: '/_content-layout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof contentRoutesPrivacyRouteImport
      parentRoute: typeof contentRoutesLayoutRoute
    }
    '/_content-layout/': {
      id: '/_content-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof contentRoutesHomeRouteImport
      parentRoute: typeof contentRoutesLayoutRoute
    }
    '/_content-layout/blog/$slug': {
      id: '/_content-layout/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof blogRoutesPostRouteImport
      parentRoute: typeof contentRoutesLayoutRoute
    }
  }
}

interface contentRoutesLayoutRouteChildren {
  contentRoutesHomeRoute: typeof contentRoutesHomeRoute
  contentRoutesPrivacyRoute: typeof contentRoutesPrivacyRoute
  contentRoutesTermsAndConditionsRoute: typeof contentRoutesTermsAndConditionsRoute
  blogRoutesIndexRoute: typeof blogRoutesIndexRoute
  blogRoutesPostRoute: typeof blogRoutesPostRoute
}

const contentRoutesLayoutRouteChildren: contentRoutesLayoutRouteChildren = {
  contentRoutesHomeRoute: contentRoutesHomeRoute,
  contentRoutesPrivacyRoute: contentRoutesPrivacyRoute,
  contentRoutesTermsAndConditionsRoute: contentRoutesTermsAndConditionsRoute,
  blogRoutesIndexRoute: blogRoutesIndexRoute,
  blogRoutesPostRoute: blogRoutesPostRoute,
}

const contentRoutesLayoutRouteWithChildren =
  contentRoutesLayoutRoute._addFileChildren(contentRoutesLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  contentRoutesLayoutRoute: contentRoutesLayoutRouteWithChildren,
  authRoutesLoginRoute: authRoutesLoginRoute,
  emailRoutesSentRoute: emailRoutesSentRoute,
  paymentsRoutesSuccessRoute: paymentsRoutesSuccessRoute,
  paymentsRoutesWebhookRoute: paymentsRoutesWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
