/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as authRoutesLoginRouteImport } from './auth/routes/login'
import { Route as brandRoutesLayoutRouteImport } from './brand/routes/layout'
import { Route as blogRoutesIndexRouteImport } from './blog/routes/index'
import { Route as paymentsRoutesWebhookRouteImport } from './payments/routes/webhook'
import { Route as paymentsRoutesSuccessRouteImport } from './payments/routes/success'
import { Route as emailRoutesSentRouteImport } from './email/routes/sent'
import { Route as brandRoutesTermsAndConditionsRouteImport } from './brand/routes/terms-and-conditions'
import { Route as brandRoutesPrivacyRouteImport } from './brand/routes/privacy'
import { Route as brandRoutesHomeRouteImport } from './brand/routes/home'
import { Route as blogRoutesPostRouteImport } from './blog/routes/post'

const authRoutesLoginRoute = authRoutesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const brandRoutesLayoutRoute = brandRoutesLayoutRouteImport.update({
  id: '/_brand-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const blogRoutesIndexRoute = blogRoutesIndexRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => brandRoutesLayoutRoute,
} as any)
const paymentsRoutesWebhookRoute = paymentsRoutesWebhookRouteImport.update({
  id: '/payments/webhook',
  path: '/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const paymentsRoutesSuccessRoute = paymentsRoutesSuccessRouteImport.update({
  id: '/payments/success',
  path: '/payments/success',
  getParentRoute: () => rootRouteImport,
} as any)
const emailRoutesSentRoute = emailRoutesSentRouteImport.update({
  id: '/emails/sent',
  path: '/emails/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const brandRoutesTermsAndConditionsRoute =
  brandRoutesTermsAndConditionsRouteImport.update({
    id: '/terms-and-conditions',
    path: '/terms-and-conditions',
    getParentRoute: () => brandRoutesLayoutRoute,
  } as any)
const brandRoutesPrivacyRoute = brandRoutesPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => brandRoutesLayoutRoute,
} as any)
const brandRoutesHomeRoute = brandRoutesHomeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => brandRoutesLayoutRoute,
} as any)
const blogRoutesPostRoute = blogRoutesPostRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => brandRoutesLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof brandRoutesHomeRoute
  '/login': typeof authRoutesLoginRoute
  '/privacy': typeof brandRoutesPrivacyRoute
  '/terms-and-conditions': typeof brandRoutesTermsAndConditionsRoute
  '/emails/sent': typeof emailRoutesSentRoute
  '/payments/success': typeof paymentsRoutesSuccessRoute
  '/payments/webhook': typeof paymentsRoutesWebhookRoute
  '/blog': typeof blogRoutesIndexRoute
  '/blog/$slug': typeof blogRoutesPostRoute
}
export interface FileRoutesByTo {
  '/login': typeof authRoutesLoginRoute
  '/': typeof brandRoutesHomeRoute
  '/privacy': typeof brandRoutesPrivacyRoute
  '/terms-and-conditions': typeof brandRoutesTermsAndConditionsRoute
  '/emails/sent': typeof emailRoutesSentRoute
  '/payments/success': typeof paymentsRoutesSuccessRoute
  '/payments/webhook': typeof paymentsRoutesWebhookRoute
  '/blog': typeof blogRoutesIndexRoute
  '/blog/$slug': typeof blogRoutesPostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_brand-layout': typeof brandRoutesLayoutRouteWithChildren
  '/login': typeof authRoutesLoginRoute
  '/_brand-layout/': typeof brandRoutesHomeRoute
  '/_brand-layout/privacy': typeof brandRoutesPrivacyRoute
  '/_brand-layout/terms-and-conditions': typeof brandRoutesTermsAndConditionsRoute
  '/emails/sent': typeof emailRoutesSentRoute
  '/payments/success': typeof paymentsRoutesSuccessRoute
  '/payments/webhook': typeof paymentsRoutesWebhookRoute
  '/_brand-layout/blog': typeof blogRoutesIndexRoute
  '/_brand-layout/blog/$slug': typeof blogRoutesPostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms-and-conditions'
    | '/emails/sent'
    | '/payments/success'
    | '/payments/webhook'
    | '/blog'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/privacy'
    | '/terms-and-conditions'
    | '/emails/sent'
    | '/payments/success'
    | '/payments/webhook'
    | '/blog'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/_brand-layout'
    | '/login'
    | '/_brand-layout/'
    | '/_brand-layout/privacy'
    | '/_brand-layout/terms-and-conditions'
    | '/emails/sent'
    | '/payments/success'
    | '/payments/webhook'
    | '/_brand-layout/blog'
    | '/_brand-layout/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  brandRoutesLayoutRoute: typeof brandRoutesLayoutRouteWithChildren
  authRoutesLoginRoute: typeof authRoutesLoginRoute
  emailRoutesSentRoute: typeof emailRoutesSentRoute
  paymentsRoutesSuccessRoute: typeof paymentsRoutesSuccessRoute
  paymentsRoutesWebhookRoute: typeof paymentsRoutesWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authRoutesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand-layout': {
      id: '/_brand-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof brandRoutesLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand-layout/blog': {
      id: '/_brand-layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof blogRoutesIndexRouteImport
      parentRoute: typeof brandRoutesLayoutRoute
    }
    '/payments/webhook': {
      id: '/payments/webhook'
      path: '/payments/webhook'
      fullPath: '/payments/webhook'
      preLoaderRoute: typeof paymentsRoutesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/success': {
      id: '/payments/success'
      path: '/payments/success'
      fullPath: '/payments/success'
      preLoaderRoute: typeof paymentsRoutesSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/sent': {
      id: '/emails/sent'
      path: '/emails/sent'
      fullPath: '/emails/sent'
      preLoaderRoute: typeof emailRoutesSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand-layout/terms-and-conditions': {
      id: '/_brand-layout/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof brandRoutesTermsAndConditionsRouteImport
      parentRoute: typeof brandRoutesLayoutRoute
    }
    '/_brand-layout/privacy': {
      id: '/_brand-layout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof brandRoutesPrivacyRouteImport
      parentRoute: typeof brandRoutesLayoutRoute
    }
    '/_brand-layout/': {
      id: '/_brand-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof brandRoutesHomeRouteImport
      parentRoute: typeof brandRoutesLayoutRoute
    }
    '/_brand-layout/blog/$slug': {
      id: '/_brand-layout/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof blogRoutesPostRouteImport
      parentRoute: typeof brandRoutesLayoutRoute
    }
  }
}

interface brandRoutesLayoutRouteChildren {
  brandRoutesHomeRoute: typeof brandRoutesHomeRoute
  brandRoutesPrivacyRoute: typeof brandRoutesPrivacyRoute
  brandRoutesTermsAndConditionsRoute: typeof brandRoutesTermsAndConditionsRoute
  blogRoutesIndexRoute: typeof blogRoutesIndexRoute
  blogRoutesPostRoute: typeof blogRoutesPostRoute
}

const brandRoutesLayoutRouteChildren: brandRoutesLayoutRouteChildren = {
  brandRoutesHomeRoute: brandRoutesHomeRoute,
  brandRoutesPrivacyRoute: brandRoutesPrivacyRoute,
  brandRoutesTermsAndConditionsRoute: brandRoutesTermsAndConditionsRoute,
  blogRoutesIndexRoute: blogRoutesIndexRoute,
  blogRoutesPostRoute: blogRoutesPostRoute,
}

const brandRoutesLayoutRouteWithChildren =
  brandRoutesLayoutRoute._addFileChildren(brandRoutesLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  brandRoutesLayoutRoute: brandRoutesLayoutRouteWithChildren,
  authRoutesLoginRoute: authRoutesLoginRoute,
  emailRoutesSentRoute: emailRoutesSentRoute,
  paymentsRoutesSuccessRoute: paymentsRoutesSuccessRoute,
  paymentsRoutesWebhookRoute: paymentsRoutesWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
