/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as authRoutesLoginRouteImport } from './auth/routes/login'
import { Route as brandRoutesLayoutRouteImport } from './brand/routes/layout'
import { Route as blogRoutesIndexRouteImport } from './blog/routes/index'
import { Route as paymentsRoutesWebhookRouteImport } from './payments/routes/webhook'
import { Route as paymentsRoutesSuccessRouteImport } from './payments/routes/success'
import { Route as newsletterRoutesConfirmRouteImport } from './newsletter/routes/confirm'
import { Route as emailRoutesSentRouteImport } from './email/routes/sent'
import { Route as brandRoutesHomeRouteImport } from './brand/routes/home'
import { Route as brandRoutesLegalRouteImport } from './brand/routes/legal'
import { Route as blogRoutesPostRouteImport } from './blog/routes/post'

const authRoutesLoginRoute = authRoutesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const brandRoutesLayoutRoute = brandRoutesLayoutRouteImport.update({
  id: '/_brand-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const blogRoutesIndexRoute = blogRoutesIndexRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => brandRoutesLayoutRoute,
} as any)
const paymentsRoutesWebhookRoute = paymentsRoutesWebhookRouteImport.update({
  id: '/payments/webhook',
  path: '/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const paymentsRoutesSuccessRoute = paymentsRoutesSuccessRouteImport.update({
  id: '/payments/success',
  path: '/payments/success',
  getParentRoute: () => rootRouteImport,
} as any)
const newsletterRoutesConfirmRoute = newsletterRoutesConfirmRouteImport.update({
  id: '/newsletter/confirm',
  path: '/newsletter/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const emailRoutesSentRoute = emailRoutesSentRouteImport.update({
  id: '/emails/sent',
  path: '/emails/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const brandRoutesHomeRoute = brandRoutesHomeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => brandRoutesLayoutRoute,
} as any)
const brandRoutesLegalRoute = brandRoutesLegalRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => brandRoutesLayoutRoute,
} as any)
const blogRoutesPostRoute = blogRoutesPostRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => brandRoutesLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof brandRoutesHomeRoute
  '/login': typeof authRoutesLoginRoute
  '/emails/sent': typeof emailRoutesSentRoute
  '/newsletter/confirm': typeof newsletterRoutesConfirmRoute
  '/payments/success': typeof paymentsRoutesSuccessRoute
  '/payments/webhook': typeof paymentsRoutesWebhookRoute
  '/blog': typeof blogRoutesIndexRoute
  '/blog/$slug': typeof blogRoutesPostRoute
  '/legal/$slug': typeof brandRoutesLegalRoute
}
export interface FileRoutesByTo {
  '/login': typeof authRoutesLoginRoute
  '/': typeof brandRoutesHomeRoute
  '/emails/sent': typeof emailRoutesSentRoute
  '/newsletter/confirm': typeof newsletterRoutesConfirmRoute
  '/payments/success': typeof paymentsRoutesSuccessRoute
  '/payments/webhook': typeof paymentsRoutesWebhookRoute
  '/blog': typeof blogRoutesIndexRoute
  '/blog/$slug': typeof blogRoutesPostRoute
  '/legal/$slug': typeof brandRoutesLegalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_brand-layout': typeof brandRoutesLayoutRouteWithChildren
  '/login': typeof authRoutesLoginRoute
  '/_brand-layout/': typeof brandRoutesHomeRoute
  '/emails/sent': typeof emailRoutesSentRoute
  '/newsletter/confirm': typeof newsletterRoutesConfirmRoute
  '/payments/success': typeof paymentsRoutesSuccessRoute
  '/payments/webhook': typeof paymentsRoutesWebhookRoute
  '/_brand-layout/blog': typeof blogRoutesIndexRoute
  '/_brand-layout/blog/$slug': typeof blogRoutesPostRoute
  '/_brand-layout/legal/$slug': typeof brandRoutesLegalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/emails/sent'
    | '/newsletter/confirm'
    | '/payments/success'
    | '/payments/webhook'
    | '/blog'
    | '/blog/$slug'
    | '/legal/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/emails/sent'
    | '/newsletter/confirm'
    | '/payments/success'
    | '/payments/webhook'
    | '/blog'
    | '/blog/$slug'
    | '/legal/$slug'
  id:
    | '__root__'
    | '/_brand-layout'
    | '/login'
    | '/_brand-layout/'
    | '/emails/sent'
    | '/newsletter/confirm'
    | '/payments/success'
    | '/payments/webhook'
    | '/_brand-layout/blog'
    | '/_brand-layout/blog/$slug'
    | '/_brand-layout/legal/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  brandRoutesLayoutRoute: typeof brandRoutesLayoutRouteWithChildren
  authRoutesLoginRoute: typeof authRoutesLoginRoute
  emailRoutesSentRoute: typeof emailRoutesSentRoute
  newsletterRoutesConfirmRoute: typeof newsletterRoutesConfirmRoute
  paymentsRoutesSuccessRoute: typeof paymentsRoutesSuccessRoute
  paymentsRoutesWebhookRoute: typeof paymentsRoutesWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authRoutesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand-layout': {
      id: '/_brand-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof brandRoutesLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand-layout/blog': {
      id: '/_brand-layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof blogRoutesIndexRouteImport
      parentRoute: typeof brandRoutesLayoutRoute
    }
    '/payments/webhook': {
      id: '/payments/webhook'
      path: '/payments/webhook'
      fullPath: '/payments/webhook'
      preLoaderRoute: typeof paymentsRoutesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/success': {
      id: '/payments/success'
      path: '/payments/success'
      fullPath: '/payments/success'
      preLoaderRoute: typeof paymentsRoutesSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirm': {
      id: '/newsletter/confirm'
      path: '/newsletter/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof newsletterRoutesConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/sent': {
      id: '/emails/sent'
      path: '/emails/sent'
      fullPath: '/emails/sent'
      preLoaderRoute: typeof emailRoutesSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand-layout/': {
      id: '/_brand-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof brandRoutesHomeRouteImport
      parentRoute: typeof brandRoutesLayoutRoute
    }
    '/_brand-layout/legal/$slug': {
      id: '/_brand-layout/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof brandRoutesLegalRouteImport
      parentRoute: typeof brandRoutesLayoutRoute
    }
    '/_brand-layout/blog/$slug': {
      id: '/_brand-layout/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof blogRoutesPostRouteImport
      parentRoute: typeof brandRoutesLayoutRoute
    }
  }
}

interface brandRoutesLayoutRouteChildren {
  brandRoutesHomeRoute: typeof brandRoutesHomeRoute
  blogRoutesIndexRoute: typeof blogRoutesIndexRoute
  blogRoutesPostRoute: typeof blogRoutesPostRoute
  brandRoutesLegalRoute: typeof brandRoutesLegalRoute
}

const brandRoutesLayoutRouteChildren: brandRoutesLayoutRouteChildren = {
  brandRoutesHomeRoute: brandRoutesHomeRoute,
  blogRoutesIndexRoute: blogRoutesIndexRoute,
  blogRoutesPostRoute: blogRoutesPostRoute,
  brandRoutesLegalRoute: brandRoutesLegalRoute,
}

const brandRoutesLayoutRouteWithChildren =
  brandRoutesLayoutRoute._addFileChildren(brandRoutesLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  brandRoutesLayoutRoute: brandRoutesLayoutRouteWithChildren,
  authRoutesLoginRoute: authRoutesLoginRoute,
  emailRoutesSentRoute: emailRoutesSentRoute,
  newsletterRoutesConfirmRoute: newsletterRoutesConfirmRoute,
  paymentsRoutesSuccessRoute: paymentsRoutesSuccessRoute,
  paymentsRoutesWebhookRoute: paymentsRoutesWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
